import { Post } from '../Types/firestoreSchema'

export const dummyAuthors: string[] = [
  'Mauricio Benck',
  'Tamqrah Blanpein',
  'Adrien Stanman',
  'Gerry Stenton',
  'Marlyn Ungarett',
  'Saunder Ewdale',
  'Sheryl Pay',
  'Odelia Mayworth',
  'Ula Bradnick',
  'Greggory Ellwell',
]

export const dummyPosts: Post[] = [
  {
    id: '1b767ec7-c9d9-4bf3-83d9-e86aa184ce9d',
    title: 'Illegal',
    summary: `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean m`,
    author: 'Tamqrah Blanpein',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 13).toString(),
  },
  {
    id: 'b6587b35-7c88-4019-b66d-a262db2e1a40',
    title: 'Bread, My Sweet, The (a.k.a. Wedding for Bella, A)',
    summary: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was bo`,
    author: 'Gerry Stenton',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 2).toString(),
  },
  {
    id: '763c8897-764a-448f-b2e8-9a63728c9fb7',
    title: 'Sanshiro Sugata Part Two (Judo Saga II) (Zoku Sugata Sanshirô)',
    summary: 'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musi',
    author: 'Saunder Ewdale',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 6).toString(),
  },
  {
    id: '8767afab-6bbb-44fe-a135-44b65b7cdea0',
    title: 'Ellen DeGeneres: The Beginning',
    summary: `Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musi`,
    author: 'Odelia Mayworth',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 13).toString(),
  },
  {
    id: 'e6cee42a-3745-4c08-b062-e7b90cefb4fa',
    title: 'Daayen Ya Baayen',
    summary: `A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring whi`,
    author: 'Greggory Ellwell',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 1).toString(),
  },
  {
    id: '6bb09cd7-661c-467e-b1bb-4447610fed72',
    title: 'Hi-Life',
    summary: `The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced`,
    author: 'Mauricio Benck',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 22).toString(),
  },
  {
    id: '353a854f-fea8-42db-a87c-adce83435b55',
    title: 'Dealer',
    summary: `The European languages are members of the same family. Their separate existence is a myth. For scien`,
    author: 'Adrien Stanman',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 30).toString(),
  },
  {
    id: '9e95c50e-dd46-4f5a-b507-7021813c627b',
    title: 'Arrival, The',
    summary: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was bo`,
    author: 'Marlyn Ungarett',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 2).toString(),
  },
  {
    id: '615ac1e4-8f13-45e9-a470-9cb5677de516',
    title: 'Toomorrow',
    summary: `How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven`,
    author: 'Sheryl Pay',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 2).toString(),
  },
  {
    id: '207aea67-a70b-43f3-9e32-7b310a1cd235',
    title: 'Ruby Cairo',
    summary: `Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies n`,
    author: 'Ula Bradnick',
    createdDate: new Date(2020, 9, 1).toString(),
    modifiedDate: new Date(2020, 9, 25).toString(),
  },
]
